///
/// File generated by cpct_aks2c CPCtelera script
/// Souce file of this conversion: assets/music.aks
/// Generation time: mié 11 nov 2020 19:37:05 CET
///

/// Song 'song_demo' metadata macros
#define song_demo_address  0x0040
#define song_demo_size     406
#define song_demo_end      0x1d5

/// Song 'song_demo' array declaration
extern void song_demo[song_demo_size];
